---
# https://pre-commit.com/
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v6.0.0
    hooks:
      - id: check-json
        exclude: |
          (?x)^(
            backup/[\d|\w|_]+\/(.*?)|
            docs/nodejs/ts_tutorial/tsconfig.json|
            path/to/file3.json
          )$
      - id: check-yaml
        args:
          - --allow-multiple-documents
      - id: check-toml
      - id: check-xml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict

  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.9
    hooks:
      - id: actionlint

  - repo: https://github.com/jackdewinter/pymarkdown
    rev: v0.9.34
    hooks:
      - id: pymarkdown
        args:
          - --config=.config/.pymarkdown.yaml
          - scan
        exclude: |
          (?x)^(
            backup/[\d|\w|_]+\/(.*?)|
            habits/.*\.md|
            path/to/file3.py
          )$

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.37.1
    hooks:
      - id: yamllint
        args:
          - -c=.config/.yamllint
        exclude: |
          (?x)^(
            backup/[\d|\w|_]+\/(.*?)|
            aqua.yaml
          )$

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.3.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [feat, fix, build, chore, ci, docs, perf, refactor, revert, style, test]
